### ISSUE TITLE
Libros de programación

### ISSUE THREAD

**Issue by alepiumetti** [Hackfun-Rosario/CosasGratisParaHacerEnInternet#1]
NOMBRE: Libros para aprender a programar
DESCRIPCIÓN: Libros en español para aprender lenguajes de programación, ciencias de la computación, metodologías de desarrollo, etc.
LINK: https://github.com/alepiumetti/free-programming-books/blob/master/free-programming-books-es.md
CATEGORÍA: Programación

**Comment by mdev88** [comment]
Agregado, gracias!
